val rbt = rosalindBiosciToolkit()

const val dna = "TGATGTGACGGGTTCGCAGGTGCCCTGTGATTAGAGTAATGAACTTCGTCCTAGCGTAAAAGTGCTCCGGCACATAGAT" +
        "TGCTTTCCCGGGATATATATGCATGTAGGAGATGTTTCCTCATGCTTCCGGTAGGCTAGTCCTACCTCATTAGTCCACTTA" +
        "ACAGTGAACCCTTTCCATCATTAGACGTGGAGAACCATTGTCGCCCCCACAAGCAGGATAAGGAGTTCATCCCCTTAAGCA" +
        "CAAAATCAAATACAAAAGGCAAGTTTGAGACTCTTGTCAAATCTACTCTTTTGCGACTCACAGGCGCAGTTGCAACAATTG" +
        "ATAAGGCTTTGAATCATTAGGAAGACCATAGAGCGAACAAGTCCTCAAACGCGAATGACGGGAGATCACTGCAGACTGTGC" +
        "TAGCTACAGCGCGCCTGCCCGTTCCTCGCCCATGGCCCAAAGAGCCCTAAACCGAGGATGGGTTCGTTTCCGAGGCTCGCG" +
        "TCCTTGCCAGTCGCACCCCTATTAATTGACGATCGTTGGTAAGTTTCCTAAATGCGCATAAGCGACTCTAATAATATGGAC" +
        "GCATCGATAGACACCTAGGTTGTAACCGTGGGGTTAAGACATATGTATTCGACAGGTCGTTTATACTAACATGGTACGTGT" +
        "GCTTCGTGAACTATCTGTCAACTGTAGGTCTCCAACGTGATGAAGTAAGCCCTTAGCGGTGGTTATGTGGCTGGGTTAGTA" +
        "CAGTACGTTTGTGTTTCCGACCCAGTATCTGCTTGCCTATGACGTGCCCCCCAGTCGGAGGAACAAGAATCAAGGCTGCTG" +
        "GATTATCATACGTATGACTGTTAAATCGA"

const val text = "TGATACTATTATACTATGATACTATTAGATACTATCCGGTATATACTATACATACTATTCATACTATCGATACTATGCGGACCACCGATACTATTGGCTATACTATATACTATATACTATATACTATCGAATACTATGCTCATACTATCTTACAATGGATGAAGCTCAGGACATACTATATGCATACTATGGATACTATGATACTATAGACGATACTATATGGATACTATTTTCATACTATTTTGTCATACTATCTATACTATGTCGTTATACTATGTGAGATACTATCATACTATGGAGGATACTATCATACTATATACTATGCAATACTATATACTATGAATACTATATACTATAATACTATCATACTATGATACTATTAAGGAACATACTATTATACTATTGCGCATACTATATACTATATACTATGGGTCGATACTATATACTATCATACTATATACTATAAGATACTATATACTATTTCAGGATACTATTATACTATATACTATCACCATACTATAATACTATGCGATACTATCAATACTATAGAATACTATATACTATATACTATAATACTATGATACTATATACTATCCGGGCGAATACTATATACTATGGGGTGGATACTATATACTATGTGTAATACTATCAATACTATATTCCATACTATTGGGCTTTCAAATACTATAAATACTATGGATACTATGGAATACTATAATACTATTATACTATCGTGATACTATCATCGTATACTATATACTATGAATACTATGATACTATAATACTATGGTATACTATTGCCAAATACTATATACTATATACTATGCCACGCGCTGAATACTATAATACTATTAGATACTATATACTAT"
const val subs = "ATACTATAT"
val motifPair = Pair(text,subs)

fun rosalindCountNucleotides() {
    //Problem 1
    println()
    print("Rosalind Count Nucleotides: ")
    println(rbt.countBases(dna))
}

fun rosalindDNACompliment() {
    //Problem 2
    println()
    print("Rosalind Reverse Compliment: ")
    println(rbt.reverseCompliment(dna))
}

fun rosalindGCContent() {
    val strands = rbt.stripFASTA("data/testFileGC-Content")
    println()
    print("Rosalind GC Content: ")
    println(rbt.gcContent(strands))
}

fun rosalindHammingDistance() {
    val pairs = rbt.readHammingPair("data/testFileHamming")
    println()
    print("Rosalind Hamming Distance: ")
    println(rbt.calculateHammingDistance(pairs))
}

fun rosalindTranscribeDNAToRNA() {
    println()
    print("Rosalind Transcribe DNA to RNA: ")
    println(rbt.transDnaToRna(dna))
}

fun rosalindMotifLocations() {
    println()
    print("Rosalind Motif Locations: ")
    println(rbt.motifLocations(motifPair))
}

fun rosalindSharedMotifs() {
    println()
    print("Rosalind Shared Motifs: ")
    val foo = rbt.stripFASTA("data/testFileSharedMotif")
    val bar = rbt.uniqMotifs(foo)
    println(rbt.largestCommonMotif(bar))
}

fun main() {
    rosalindCountNucleotides()
    rosalindDNACompliment()
    rosalindGCContent()
    rosalindHammingDistance()
    rosalindTranscribeDNAToRNA()
    rosalindMotifLocations()
    rosalindSharedMotifs()
}

