class Motif {

    fun motifLocations(strand: String, subs: String) {
        for (i in 0..strand.length - subs.length) {
            if (strand.substring(i, i + subs.length).indexOf(subs) == 0) {
                print((i + 1).toString() + " ")
            }
        }
    }
}

val text =
    "TGATACTATTATACTATGATACTATTAGATACTATCCGGTATATACTATACATACTATTCATACTATCGATACTATGCGGACCACCGATACTATTGGCTATACTATATACTATATACTATATACTATCGAATACTATGCTCATACTATCTTACAATGGATGAAGCTCAGGACATACTATATGCATACTATGGATACTATGATACTATAGACGATACTATATGGATACTATTTTCATACTATTTTGTCATACTATCTATACTATGTCGTTATACTATGTGAGATACTATCATACTATGGAGGATACTATCATACTATATACTATGCAATACTATATACTATGAATACTATATACTATAATACTATCATACTATGATACTATTAAGGAACATACTATTATACTATTGCGCATACTATATACTATATACTATGGGTCGATACTATATACTATCATACTATATACTATAAGATACTATATACTATTTCAGGATACTATTATACTATATACTATCACCATACTATAATACTATGCGATACTATCAATACTATAGAATACTATATACTATATACTATAATACTATGATACTATATACTATCCGGGCGAATACTATATACTATGGGGTGGATACTATATACTATGTGTAATACTATCAATACTATATTCCATACTATTGGGCTTTCAAATACTATAAATACTATGGATACTATGGAATACTATAATACTATTATACTATCGTGATACTATCATCGTATACTATATACTATGAATACTATGATACTATAATACTATGGTATACTATTGCCAAATACTATATACTATATACTATGCCACGCGCTGAATACTATAATACTATTAGATACTATATACTAT"
val subs = "ATACTATAT"
val foo = Motif()
foo.motifLocations(text, subs)